[package]
name = "cli"
version = "0.2.1"
edition = "2021"

[dependencies]
rs-tickers = { path = "../rs-tickers" }
atty = "0.2.14"
either = "1.6.1"
once_cell = "1.9.0"
serde_json = "1.0.74"
structopt = "0.3.25"
