[package]
name = "rs-tickers"
version = "0.3.0"
edition = "2021"

[dependencies]
log = "0.4.14"
reqwest = { version = "0.11.8", features = ["blocking", "gzip"] }
scraper = "0.12.0"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
